In [2]:
%cd /Users/genevieveberent/Desktop

/Users/genevieveberent/Desktop


In [3]:
import pandas as pd
import numpy as np

In [4]:
students = pd.read_csv('student-math.csv')

In [5]:
students.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other ...   
3     GP   F   15       U     GT3       T     4     2   health  services ...   
4     GP   F   16       U     GT3       T     3     3    other     other ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [6]:
#Convert the target column from a grade percentage to a pass/fail
students['Pass_Fail'] = np.where(students['G3'] < 12, 0, 1)

In [29]:
students.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher   
1     GP   F   17       U     GT3       T     1     1  at_home     other   
2     GP   F   15       U     LE3       T     1     1  at_home     other   
3     GP   F   15       U     GT3       T     4     2   health  services   
4     GP   F   16       U     GT3       T     3     3    other     other   

     ...    freetime goout  Dalc  Walc  health absences  G1  G2  G3 Pass_Fail  
0    ...           3     4     1     1       3        6   5   6   6         0  
1    ...           3     3     1     1       3        4   5   5   6         0  
2    ...           3     2     2     3       3       10   7   8  10         0  
3    ...           2     2     1     1       5        2  15  14  15         1  
4    ...           3     2     1     2       5        4   6  10  10         0  

[5 rows x 34 columns]

In [30]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 34 columns):
school        395 non-null object
sex           395 non-null object
age           395 non-null int64
address       395 non-null object
famsize       395 non-null object
Pstatus       395 non-null object
Medu          395 non-null int64
Fedu          395 non-null int64
Mjob          395 non-null object
Fjob          395 non-null object
reason        395 non-null object
guardian      395 non-null object
traveltime    395 non-null int64
studytime     395 non-null int64
failures      395 non-null int64
schoolsup     395 non-null object
famsup        395 non-null object
paid          395 non-null object
activities    395 non-null object
nursery       395 non-null object
higher        395 non-null object
internet      395 non-null object
romantic      395 non-null object
famrel        395 non-null int64
freetime      395 non-null int64
goout         395 non-null int64
Dalc          395 no

In [31]:
dummies_col = ['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob', 
               'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities',
              'nursery', 'higher', 'internet', 'romantic']
df_dummies = pd.get_dummies(students[dummies_col])

In [32]:
students = students.drop(dummies_col, axis=1)

students = df_dummies.join(students)
students.head()

school_GP  school_MS  sex_F  sex_M  address_R  address_U  famsize_GT3  \
0          1          0      1      0          0          1            1   
1          1          0      1      0          0          1            1   
2          1          0      1      0          0          1            0   
3          1          0      1      0          0          1            1   
4          1          0      1      0          0          1            1   

   famsize_LE3  Pstatus_A  Pstatus_T    ...      freetime  goout  Dalc  Walc  \
0            0          1          0    ...             3      4     1     1   
1            0          0          1    ...             3      3     1     1   
2            1          0          1    ...             3      2     2     3   
3            0          0          1    ...             2      2     1     1   
4            0          0          1    ...             3      2     1     2   

   health  absences  G1  G2  G3  Pass_Fail  
0       3         6   5   6   6          0  
1       3         4   5   5   6          0  
2       3        10   7   8  10          0  
3       5         2  15  14  15          1  
4       5         4   6  10  10          0  

[5 rows x 60 columns]

In [33]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 60 columns):
school_GP            395 non-null uint8
school_MS            395 non-null uint8
sex_F                395 non-null uint8
sex_M                395 non-null uint8
address_R            395 non-null uint8
address_U            395 non-null uint8
famsize_GT3          395 non-null uint8
famsize_LE3          395 non-null uint8
Pstatus_A            395 non-null uint8
Pstatus_T            395 non-null uint8
Mjob_at_home         395 non-null uint8
Mjob_health          395 non-null uint8
Mjob_other           395 non-null uint8
Mjob_services        395 non-null uint8
Mjob_teacher         395 non-null uint8
Fjob_at_home         395 non-null uint8
Fjob_health          395 non-null uint8
Fjob_other           395 non-null uint8
Fjob_services        395 non-null uint8
Fjob_teacher         395 non-null uint8
reason_course        395 non-null uint8
reason_home          395 non-null uint8
reason_other   

In [34]:
X = students.drop(['G3', 'Pass_Fail'], axis=1)
y = students['Pass_Fail']

In [35]:
from sklearn import cross_validation

In [36]:
X_train, X_test, y_train, y_test = cross_validation.train_test_split(
    X, y, test_size=0.2, random_state=50)
print(X_train.shape)
print(y_train.shape)

(316, 58)
(316,)


Data:  Student Performance Data Set
https://archive.ics.uci.edu/ml/datasets/student+performance

In [37]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

lr = LogisticRegression()
lr.fit(X_train, y_train)

predictions_1 = lr.predict(X_test)

print('Logistic Regression Classification')
print('Accuracy', accuracy_score(predictions_1, y_test))
print('Confusion Matrix\n', confusion_matrix(predictions_1, y_test))
print('Classification Matrix\n', classification_report(predictions_1, y_test))



Logistic Regression Classification
Accuracy 0.860759493671
Confusion Matrix
 [[45  6]
 [ 5 23]]
Classification Matrix
              precision    recall  f1-score   support

          0       0.90      0.88      0.89        51
          1       0.79      0.82      0.81        28

avg / total       0.86      0.86      0.86        79



In [40]:
#Support Vector Machine
from sklearn.svm import SVC

svc = SVC()
svc.fit(X_train, y_train)

predictions_2 = svc.predict(X_test)

print('SVM Classification')
print('Accuracy', accuracy_score(predictions_2, y_test))
print('Confusion Matrix\n', confusion_matrix(predictions_2, y_test))
print('Classification Matrix\n', classification_report(predictions_2, y_test))



SVM Classification
Accuracy 0.886075949367
Confusion Matrix
 [[43  2]
 [ 7 27]]
Classification Matrix
              precision    recall  f1-score   support

          0       0.86      0.96      0.91        45
          1       0.93      0.79      0.86        34

avg / total       0.89      0.89      0.88        79



In [42]:
#Decsion Tree
from sklearn import preprocessing, tree

dtree = tree.DecisionTreeClassifier(criterion='entropy')
dtree.fit(X_train, y_train)

predictions_3 = dtree.predict(X_test)

print('Decision Tree Classification')
print('Accuracy', accuracy_score(predictions_3, y_test))
print('Confusion Matrix\n', confusion_matrix(predictions_3, y_test))
print('Classification Matrix\n', classification_report(predictions_3, y_test))



Decision Tree Classification
Accuracy 0.936708860759
Confusion Matrix
 [[47  2]
 [ 3 27]]
Classification Matrix
              precision    recall  f1-score   support

          0       0.94      0.96      0.95        49
          1       0.93      0.90      0.92        30

avg / total       0.94      0.94      0.94        79

